blank_issues_enabled: false
contact_links:
  - name: Need help or have a question?
    url: https://github.com/fish-lgbt/studio/issues
    about: If you have a question or need help, please open an issue for support.
